### ISSUE TITLE
Yggdrasil?

### ISSUE THREAD

**Issue by makew0rld** [p2pstuff/PeerDNS#2]
I'd like to use this with [Yggdrasil](https://yggdrasil-network.github.io/) as well. Would it be possible to add support for that? Something more dynamic would be useful, such as being able to add and remove peers to the trustedList from the commandline as the daemon is running. That way Yggdrasil or other peers could be added without you having to write some support module and test it every time. Thanks!

This is really cool project btw, it's something I've sorta thought about it my head, it's awesome to see it being developed.

**Comment by Alexis211** [comment]
Hi, thanks for your comment!

I'm not familiar with Yggdrasil, but it should be quite easy to integrate. The code to integrate with CJDNS is just a call to the CJDNS admin API plus 10 lines to add the neighbor list to PeerDNS automatically, it should be very simple to do the same with Yggdrasil if they have such an API.

In the meantime, you can edit your trustlist from the command line by issuing PeerDNS API calls via Curl:
```
# Get the trust list
curl localhost:14123/api/privileged/trustlist
# Add a peer
curl localhost:14123/api/privileged/trustlist -d '{"action":"add","ip":"fc00:1234::1","name":"Test peer","api_port":14123,"weight":0.5}' -v -H "Content-Type: application/json"
# Remove a peer
curl localhost:14123/api/privileged/trustlist -d '{"action":"del","ip":"fc00:1234::1"}' -v -H "Content-Type: application/json"
```
I guess adding a CLI tool for this would be useful.

**Comment by makew0rld** [comment]
Thanks for the response! I'll look into adding Yggdrasil, but I don't know Elixir, so we'll see. The API sounds good though, and while a CLI tool would be useful, it works like this too. Is the full API documented somewhere?

**Comment by Alexis211** [comment]
I've started documenting the API in `doc/api.md` but it is not complete yet.

**Comment by makew0rld** [comment]
I'm tempted to just write a bash script to add peers instead using the API, since I don't know Elixir, and it's sort of hard to decipher what you've done in `cjdns.ex`.

**Comment by makew0rld** [comment]
@Alexis211 Will adding the peers be permanent? It should not remember them after a reboot, no?

**Comment by Alexis211** [comment]
The trust list is saved on each add/remove and is loaded when PeerDNS restarts. If you need a different behaviour that can absolutely be done, just please open a new issue and describe your use case.

**Comment by makew0rld** [comment]
Will do.

**Comment by makew0rld** [comment]
#4

**Comment by Alexis211** [comment]
Support for Yggdrasil peers has been added. Please update your config file. If you use the Unix socket for Yggdrasil admin, PeerDNS needs to run as a user that has rights to that socket.

**Comment by makew0rld** [comment]
That is great to hear, but on most systems it requires root access (through sudo) to use the socket. How can that be done without running the whole process as root?

**Comment by Alexis211** [comment]
On my system the socket had g+rw, meaning that any user in the group `yggdrasil` can access it. If you are running PeerDNS as the user `peerdns`, you need to add peerdns to the yggdrasil group: `gpasswd -a peerdns yggdrasil`

**Comment by makew0rld** [comment]
Hmm ok, I'll try thanks.
