### ISSUE TITLE
Forget peers after restart

### ISSUE THREAD

**Issue by makew0rld** [p2pstuff/PeerDNS#4]
It'd be nice to have a way in the API to add peers that get forgotten afterward. That way I could add direct Yggdrasil peers with a bash script for example, but not worry about them being retained after I shut my node down and they possibly move out of range. 

These peers would still show up in the trustlist and everything, but they just wouldn't stay after a restart.

**Comment by yangm97** [comment]
A bit unrelated but I think it would be useful to cache clearnet names across restarts.

**Comment by makew0rld** [comment]
@yangm97 @Alexis211 I was thinking to separate adding API calls, one that remembers the peer and one that doesn't.

**Comment by Alexis211** [comment]
So I'm thinking of the following improvements:

- several peer lists (just like we have several domain name lists)
- a list can be defined "temporary" in the config file -> won't be saved to disk
- API call to clear a list

Does that sound good?

**Comment by makew0rld** [comment]
That all sounds good. Maybe by default a Main and CJDNS list?

**Comment by yangm97** [comment]
@makeworld-the-better-one I don't see a need for splitting peers into two (possibly three if you count yggdrasil) lists.

**Comment by makew0rld** [comment]
@yangm97 it would allow for the differentiation between real world local peers and global clearnet ones, and allow for the easy unpeering of specific peers. It would make it a lot easier to write this Yggdrasil bash script.

**Comment by yangm97** [comment]
> it would allow for the differentiation between real world local peers and global clearnet ones

You can do that by looking at the address. I think we should be neutral whenever possible about addresses, maybe like libp2p.

**Comment by Alexis211** [comment]
Multiple peer lists have been implemented. Warning: the config file changed and the API endpoints as well! Tell me if you have problems.

**Comment by makew0rld** [comment]
Awesome, thanks! I'll test it out at some point.
