### ISSUE TITLE
Non-ascii domain registration doesn't follow the spec

### ISSUE THREAD

**Issue by yangm97** [p2pstuff/PeerDNS#8]
Right now, the webui/api allow you to register invalid domains (such as taubaté.mesh), instead of converting them into the dns standard for non ascii chars (resulting in a domain which would look like xn--taubat-gva.mesh).

Ideally, the webui/api should do the conversion on the fly (and maybe show the resolved domain aside) and reject unresolved/invalid domains.

![urdmmzsjfxymamqhwoulehvq](https://user-images.githubusercontent.com/4412002/53289155-14b8d380-3771-11e9-9162-aa2b972d9681.png)

**Comment by Alexis211** [comment]
Just commited a fix, please tell me if you still find places in the UI where conversion is not done correctly.

**Comment by yangm97** [comment]
I think you covered it all. Thanks.
